# Multiple Variable Analisys Exercise

## Working with diamonds dataset

### Diamonds price histogram by color

```{r}
library(ggplot2)

data(diamonds)
ggplot(aes(x = price, fill = cut), data = diamonds)+
  facet_wrap( ~ color )+
  scale_x_log10()+
  geom_histogram()+
  scale_fill_brewer(type = 'qual')
```

### Price vs Table Scatter

```{r}
ggplot(aes(x = table, y = price,color = cut), data = diamonds)+
  geom_point()+
  scale_x_continuous(limits= c(50,80), breaks = seq(50, 80, 2))+
  scale_color_brewer(type = 'qual')
```

### Diamond volume vs price

```{r}
diamonds$volume <- diamonds$x*diamonds$y*diamonds$z
summary(diamonds$volume)
ggplot(aes(y=price, x=volume, color=clarity), 
       data=subset(diamonds, volume<=quantile(volume, 0.99)))+
  geom_point()+
  scale_y_log10()+
  scale_color_brewer(type = 'div')
```

## Facebook dataset

### Friendship initiated vs Tenure

```{r}
pf <- read.delim('pseudo_facebook.tsv')
str(pf)
pf$prop_initiated <- pf$friendships_initiated/pf$friend_count
summary(pf$prop_initiated)
```
```{r}
pf$year_joined <- floor(2014 - pf$tenure / 365)
pf$year_joined.bucket <- cut(x=pf$year_joined, breaks = c(2004,2009,2011,2012,2014))
summary(pf$tenure)
table(pf$prop_initiated)

ggplot(aes(y = prop_initiated, x=tenure, color=year_joined.bucket), 
       data=subset(pf, !is.na(prop_initiated) & !is.na(year_joined.bucket)))+
  geom_line(stat = 'summary', fun.y = median)
```

### Friendship initiated vs Tenure - Smooth

```{r}
ggplot(aes(y = prop_initiated, x=tenure, color=year_joined.bucket), 
       data=subset(pf, !is.na(prop_initiated) & !is.na(year_joined.bucket)))+
  geom_smooth()
```

```{r}
by(pf$prop_initiated, pf$year_joined.bucket, summary)
```

## Back to diamonds dataset

### Price/carat ratio

```{r, results=asis}
ggplot(aes(y=price/carat, x=cut, color=color), data=diamonds)+
  facet_wrap( ~clarity )+
  geom_jitter()+ #also works with: geom_point(position = position_jitter(h=0))+
  scale_color_brewer(type = 'div')

```

## 

```{r}
require(xlsx)
library('tidyr')
library('dplyr')

dados <- array(c('Indicator_TC male ASM.xlsx','M','TC',
                 'Indicator_TC female ASM.xlsx','F','TC',
                 'Indicator_BMI male ASM.xlsx','M','BMI',
                 'Indicator_BMI female ASM.xlsx','F','BMI',
                 'Indicator_SBP male ASM.xlsx','M','SBP',
                 'Indicator_SBP female ASM.xlsx','F','SBP'), dim=c(3,6,2))

print(dados)

#health_risk <- read.xlsx('Indicator_TC male ASM.xlsx', sheetIndex = 1, check.names = F)
#health_risk$gender <- 'M'
#health_risk$indicator <- 'TC'
#names(health_risk)[1] <- "country"

rm(health_risk)
rm(health_risk_tmp)

for (i in 1:6) {
  print(dados[3*(i-1)+1])
  print(dados[3*(i-1)+2])
  print(dados[3*(i-1)+3])
  
  
  if (!exists("health_risk")) {
    
    health_risk <- read.xlsx(dados[3*(i-1)+1], sheetIndex = 1, check.names = F)
    health_risk$gender <- dados[3*(i-1)+2]
    health_risk$indicator <- dados[3*(i-1)+3]
    names(health_risk)[1] <- "country"
    
  } else {
    health_risk_tmp <- read.xlsx(dados[3*(i-1)+1], sheetIndex = 1, check.names = F)
    health_risk_tmp$gender <- dados[3*(i-1)+2]
    health_risk_tmp$indicator <- dados[3*(i-1)+3]
    names(health_risk_tmp)[1] <- "country"
    
    health_risk <- bind_rows(health_risk, health_risk_tmp)
    
  }
  
}

rm(health_risk_tmp)

health_risk <- gather(health_risk, "year", "value", 2:30)
health_risk$gender <- factor(health_risk$gender)
health_risk$indicator <- factor(health_risk$indicator)
```